```mermaid
flowchart TB
  subgraph EDGE[Edge & Entry]
    CF[CloudFront]
    WAF[WAF]
    APIGW[API Gateway]
  end
  subgraph ING[Ingestion]
    L1[Lambda Ingest\nValidate & PII scrub]
    KDS[Kinesis Data Streams]
  end
  subgraph STR[Streaming & Near-RT]
    SP[Lambda Stream Processor]
    FH[Kinesis Firehose]
    OS[OpenSearch (Cognito Dashboards)]
  end
  subgraph LAKE[Data Lake & Analytics]
    S3[(S3 Data Lake\nParquet + partitions)]
    GLUE[Glue Catalog + Crawler]
    ATH[Athena WorkGroup]
    QS[QuickSight]
    RS[Redshift Serverless (optional)]
  end
  subgraph SEC[Security & Ops]
    KMS[KMS CMK]
    IAM[IAM least privilege]
    COG[Cognito]
    CW[CloudWatch Logs & Alarms]
    DLQ[S3 bad-events / SQS DLQ]
  end
  CF --> WAF --> APIGW --> L1 --> KDS
  KDS --> SP --> FH --> S3 --> GLUE --> ATH --> QS
  SP --> OS
  S3 --> KMS
  APIGW --> CW
  L1 --> DLQ
  COG --> OS
```